---

name: unet

gops: [478.052300576]

shapes:
  - [[1, 3, 572, 572]]

precision: true

model: $(home)/unet.onnx

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(model)
    --input_shapes [$(shape_param)]
    --mean 0.0,0.0,0.0
    --scale 0.0039216,0.0039216,0.0039216
    --pixel_format rgb
    --test_input $(root)/dataset/samples/dog.jpg
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/$(name).mlir

# mlir_calibration:
#   run_calibration.py $(workdir)/$(name).mlir
#     --dataset $(mlir_cali_set)
#     --input_num 100
#     -o $(workdir)/calitable

BM1684X:
  deploy:
    - model_deploy.py  --mlir $(workdir)/$(name).mlir
        --quantize F32
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_$(target)_f32.bmodel
    - model_deploy.py  --mlir $(workdir)/$(name).mlir
        --quantize F16
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_$(target)_f16.bmodel
    - model_deploy.py --mlir $(workdir)/$(name).mlir
        --quantize INT8
        --calibration_table $(home)/calitable
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.80,0.80
        --model $(workdir)/$(name)_$(target)_int8_sym.bmodel
